SonarSource/sonar-update-center

.travis.yml
README.md
pom.xml
sonar-update-center-common/pom.xml
sonar-update-center-common/src/main/java/org/sonar/updatecenter/common/Release.java
sonar-update-center-common/src/main/java/org/sonar/updatecenter/common/UpdateCenterDeserializer.java
sonar-update-center-common/src/main/java/org/sonar/updatecenter/common/UpdateCenterSerializer.java
sonar-update-center-common/src/test/java/org/sonar/updatecenter/common/ReleaseTest.java
sonar-update-center-common/src/test/java/org/sonar/updatecenter/common/UpdateCenterDeserializerTest.java
sonar-update-center-common/src/test/java/org/sonar/updatecenter/common/UpdateCenterSerializerTest.java
sonar-update-center-common/src/test/resources/org/sonar/updatecenter/common/UpdateCenterDeserializerTest/updates.properties
sonar-update-center-mojo/pom.xml

See https://jira.sonarsource.com/browse/UPC-105
Relates to https://github.com/SonarSource/sonar-update-center-properties/pull/37

UPC-105 Provide Edition specific download URLs for SonarQube

---

README.md
pom.xml

Travis settings have already been updated.

Analyse code on next.sonarqube.com but not SonarCloud

---

sonar-update-center-mojo/src/test/java/org/sonar/updatecenter/mojo/GenerateMetadataMojoTest.java

I thought my last PR would still pass the QG once merged... Shouldn't have. I didn't notice we already had some tests for `HttpDownloader`, via `GenerateMetadataMojoTest`. I've increased the coverage a bit. Ideally we would test GET and HEAD methods as well, but I'm not sure how to achieve that.

Improve test coverage (fix QG)

---

sonar-update-center-mojo/src/main/java/org/sonar/updatecenter/mojo/GenerateMetadataMojo.java
sonar-update-center-mojo/src/test/java/org/sonar/updatecenter/mojo/GenerateMetadataMojoTest.java

See https://jira.sonarsource.com/browse/UPC-107
See https://github.com/SonarSource/sonar-update-center-properties/pull/63 for the sonar-update-center-properties part.

UPC-107 Allow the mojo to be used for validation only

---

sonar-update-center-mojo/src/main/resources/org/sonar/updatecenter/mojo/editions/editions-template.html.ftl
sonar-update-center-mojo/src/main/resources/org/sonar/updatecenter/mojo/matrix-template.html.ftl
sonar-update-center-mojo/src/test/resources/org/sonar/updatecenter/mojo/CompatibilityMatrixTest/compatibility-matrix.html

See https://jira.sonarsource.com/browse/UPC-108
And https://docs.sonarqube.org/latest/instance-administration/plugin-version-matrix/ (pretty, innit?)

UPC-108 Correct CSS import

---

.github/workflows/release.yml

update release.yml to latest version

---

sonar-update-center-common/src/main/java/org/sonar/updatecenter/common/PluginReferential.java
sonar-update-center-common/src/test/java/org/sonar/updatecenter/common/PluginReferentialTest.java

Sibling PR: https://github.com/SonarSource/sonar-update-center-properties/pull/288

UPC-122 remove bundled plugins

---

sonar-update-center-common/src/main/java/org/sonar/updatecenter/common/Plugin.java
sonar-update-center-common/src/main/java/org/sonar/updatecenter/common/UpdateCenterDeserializer.java
sonar-update-center-common/src/test/java/org/sonar/updatecenter/common/UpdateCenterDeserializerTest.java
sonar-update-center-common/src/test/resources/org/sonar/updatecenter/common/UpdateCenterDeserializerTest/splitFileFormat/nominal/abap.properties
sonar-update-center-common/src/test/resources/org/sonar/updatecenter/common/UpdateCenterDeserializerTest/splitFileFormat/nominal/php.properties
sonar-update-center-common/src/test/resources/org/sonar/updatecenter/common/UpdateCenterDeserializerTest/updates.properties
sonar-update-center-mojo/src/main/java/org/sonar/updatecenter/mojo/CompatibilityMatrix.java
sonar-update-center-mojo/src/main/java/org/sonar/updatecenter/mojo/PluginModel.java
sonar-update-center-mojo/src/main/resources/org/sonar/updatecenter/mojo/matrix-template.html.ftl
sonar-update-center-mojo/src/test/java/org/sonar/updatecenter/mojo/CompatibilityMatrixTest.java
sonar-update-center-mojo/src/test/resources/org/sonar/updatecenter/mojo/CompatibilityMatrixTest/compatibility-matrix.html

UPC-75 + UPC-124 remove bundled concept from the code

---

.github/workflows/release.yml

Update GitHub Action to actually do a release

---

.cirrus.star
.cirrus.yml

BUILD-2283: Migrate to CirrusCI on AWS

---

pom.xml

Update parent to v68.0.0.247

---

pom.xml
sonar-update-center-common/pom.xml
sonar-update-center-mojo/pom.xml

Bump version to 1.32-SNAPSHOT

---

.cirrus.yml

https://sonarsource.atlassian.net/browse/UPC-135

UPC-135 Move away of GCP promote function

---

sonar-update-center-common/src/main/java/org/sonar/updatecenter/common/UpdateCenterSerializer.java
sonar-update-center-common/src/test/java/org/sonar/updatecenter/common/UpdateCenterSerializerTest.java

UPC-139 Publish new properties to output file

---

pom.xml
sonar-update-center-common/pom.xml
sonar-update-center-mojo/pom.xml

Prepare for next development iteration

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/PullRequestClosed.yml
.github/workflows/PullRequestCreated.yml
.github/workflows/RequestReview.yml
.github/workflows/SubmitReview.yml

[UPC-150](https://sonarsource.atlassian.net/browse/UPC-150)
The new YML are replacing the old `synchronize-jira.yml` (if present)
Make sure the files in the PR are the same as these
[PullRequestClosed.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestClosed.yml)
[PullRequestCreated.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestCreated.yml)
[RequestReview.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/RequestReview.yml)
[SubmitReview.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/SubmitReview.yml)
⚠️ Please make sure that `PullRequestCreated.yml` has the correct Jira project on the last line! …

UPC-150 Add Jira integration

---

pom.xml
sonar-update-center-common/pom.xml
sonar-update-center-mojo/pom.xml

NO-JIRA next release cycle

---

.github/workflows/PullRequestClosed.yml

[UPC-155](https://sonarsource.atlassian.net/browse/UPC-155)
This will enable the automation to close issues that it created, to keep things more cleaned up.
Manually created issues will not be affected.
[UPC-155]: https://sonarsource.atlassian.net/browse/UPC-155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UPC-155 Autoclose issues created by Jira integration

---

.cirrus.yml
.mvn/develocity.xml
.mvn/extensions.xml

[SONAR-24808](https://sonarsource.atlassian.net/browse/SONAR-24808)
.
[SONAR-24808]: https://sonarsource.atlassian.net/browse/SONAR-24808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SONAR-24808 onboarding sonar-update-center on develocity

---

.github/workflows/unified-dogfooding.yml
pom.xml

UPC-159 add scans on SonarCloud
